apiVersion: v1
kind: Service
metadata:
  name: sample-kubernetes-go-service
spec:
  selector:
    app.kubernetes.io/name: sample-kubernetes-go # <- here the service mapps the deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080