apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-kubernetes-go-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /go-kubernetes
        pathType: Prefix
        backend:
          service:
            name: sample-kubernetes-go-service
            port:
              number: 80
